version: '3.7'

services:
  postgres:
    image: 'postgres:10.7'
    container_name: ts-backend-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ts-backend-test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
